### ISSUE TITLE
UI changes to dark theme unexpectedly

### ISSUE THREAD

**Issue by qkevinto** [ColdGrub1384/Pisth#9]
The app unexpectedly switches to the dark theme and remains that way until the app is restarted.

The purple text on the dark theme is also fairly inaccessible as well due to the low contrast and makes it rather hard to make out the icons and text.

Steps to reproduce:

1. Start a connect with SFTP or just regular SSH
2. Tap on Bookmarks to go back to the list of connections

UI will remain in a dark theme state, even though on app launch it is light themed.

**Comment by ColdGrub1384** [comment]
That's expected. The main screen of the app is the "Bookmarks" view. Then when a connection is opened, the screen is replaced by the terminal or the file browser. So, when the "Bookmarks" button is pressed, instead of returning to the bookmarks, the bookmarks are presented on top of the connection with a dark theme on iPhone. On iPad, the app uses a split view so the connection is not completely hidden: 

![iPad](https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/c9/c5/6a/c9c56a86-90bf-b4be-7877-7c7baca80264/mzl.oeyyzjyn.png/0x0ss.jpg)

I wanted to do something like [GBA4iOS](https://gba4iosap.com):

<img width="50%" src="http://www.gba4iosapp.com/images/new_ui/main_menu_emerald.png">

<img width="70%" src="http://www.gba4iosapp.com/images/download/gba4ios2_devices.png">

And for the terminal dark theme with purple text, I will make the text lighter.

**Comment by ColdGrub1384** [comment]
I made the dark terminal theme more readable, I think it's better now: 53b23a50d70513c7122b9eda88e7e3211df1d756

![simulator screen shot - ipad pro 11-inch - 2018-12-02 at 11 41 32](https://user-images.githubusercontent.com/19255527/49341102-a22fd000-f627-11e8-87f1-a01023361d7a.png)

(The buttons are red because I make them red when I'm debugging)

**Comment by qkevinto** [comment]
Ahh, understood! Thanks for clarifying, as it didn't immediately occur to me what was going on and felt a bit like a bug. Great work and looking forward to the next release!
